// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddGameToLibrary(arg1:string):Promise<string>;

export function GetSteamFeatured():Promise<string>;

export function SearchSteamGames(arg1:string):Promise<string>;
