// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddGameToLibrary(arg1) {
  return window['go']['main']['App']['AddGameToLibrary'](arg1);
}

export function GetSteamFeatured() {
  return window['go']['main']['App']['GetSteamFeatured']();
}

export function SearchSteamGames(arg1) {
  return window['go']['main']['App']['SearchSteamGames'](arg1);
}
